### ISSUE TITLE
Entry Point for SPAs

### ISSUE THREAD

**Issue by jon49** [joakimunge/denoliver#19] opened 2020-07-19 20:54 UTC
It would be nice to have an entry point for a SPA. Like if the html file is not there then look for a `404.html` file and redirect to there. Ideally be able to have different `404.html` files. Like if I request `/app/something/here` and `/app/something/here/index.html` doesn't exist then look for `/app/something/here/404.html` then `/app/something/404.html` then `/app/404.html` and finally `404.html`. And then default to your 404 file if none of those exists.

**Comment by joakimunge** [comment] 2020-08-17 11:23
Hi @jon49, thanks for the suggestion.

I will release version 2 in the coming days which has an optional entrypoint for SPAs, although not quite with the functionality you wish for. I'm not sure if I feel the feature of traversing the folder structure for possible `404.html` file is something I had in mind for denoliver, as I think that's more up to the App/SPA it self to decide how it want to handle those cases.

That being said, I will definitely consider it and, if it is something you feel strongly about I will gladly accept a PR.

**Comment by jon49** [comment] 2020-08-17 19:02
Yeah, using 404.html is a bit of hack that another one used. I would definitely prefer a cleaner way of doing this. Thanks for make it SPA friendly!

**Comment by joakimunge** [comment] 2020-08-18 09:31
> Yeah, using 404.html is a bit of hack that another one used. I would definitely prefer a cleaner way of doing this. Thanks for make it SPA friendly!

You're welcome. I have just merged v2 which includes en optional entrypoint for SPAs. Please let me know if you encounter any issues!

**Comment by joakimunge** [comment] 2022-01-31 12:13
Closing this because the suggestion is not intended behaviour!

Thanks for reaching out :)

**Closed by joakimunge** 2022-01-31 12:13 UTC
Labels: wontfix, suggestion
